# Generated by Django 5.1.7 on 2025-06-04 05:07

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=90, scale=None, size=[400, 400], upload_to='posts/images/', verbose_name='Post Image'),
        ),
    ]
