# Generated by Django 5.1.6 on 2025-06-26 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestResult',
        ),
    ]
