# Generated by Django 5.1.7 on 2025-06-04 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creadted_at',
            new_name='created_at',
        ),
    ]
