# Generated by Django 5.1.6 on 2025-06-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_creadted_at_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('HH', '한화'), ('WO', '키움'), ('HT', 'KIA'), ('LG', 'LG'), ('OB', '두산'), ('SS', '삼성'), ('LT', '롯데'), ('NC', 'NC'), ('KT', 'KT'), ('SSG', 'SSG'), ('ETC', '일반')], default='ETC', max_length=10, verbose_name='카테고리'),
        ),
    ]
