server {
    listen 80;
    server_name _;

    location /static/ {
        alias /home/ubuntu/tothe_ballpark/staticfiles/;
    }

    location / {
        include uwsgi_params;
        uwsgi_pass unix:/home/ubuntu/tothe_ballpark/tmp/baseball.sock;
    }
}
