# Generated by Django 5.1.6 on 2025-06-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='프로필 이미지'),
        ),
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.CharField(blank=True, choices=[('', '응원팀을 선택해주세요!'), ('SK', 'SSG 랜더스'), ('LG', 'LG 트윈스'), ('KT', 'KT 위즈'), ('NC', 'NC 다이노스'), ('OB', '두산 베어스'), ('SS', '삼성 라이온즈'), ('LT', '롯데 자이언츠'), ('WO', '키움 히어로즈'), ('HH', '한화 이글스'), ('HT', 'KIA 타이거즈')], max_length=10, null=True, verbose_name='My Team'),
        ),
    ]
