# Generated by Django 5.2.3 on 2025-06-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='auth/images/', verbose_name='프로필 이미지'),
        ),
    ]
