# Generated by Django 5.1.6 on 2025-06-10 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_useremail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='useremail',
        ),
    ]
