# Generated by Django 5.1.6 on 2025-06-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_image_alter_user_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='auth/images/', verbose_name='프로필 이미지'),
        ),
    ]
