# Generated by Django 5.2.1 on 2025-06-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.CharField(blank=True, choices=[('', '응원하시는 팀을 선택해주세요'), ('SK', 'SSG 랜더스'), ('LG', 'LG 트윈스'), ('KT', 'KT 위즈'), ('NC', 'NC 다이노스'), ('OB', '두산 베어스'), ('SS', '삼성 라이온즈'), ('LT', '롯데 자이언츠'), ('WO', '키움 히어로즈'), ('HH', '한화 이글스'), ('HT', 'KIA 타이거즈')], max_length=10, null=True, verbose_name='My Team'),
        ),
    ]
