# Generated by Django 5.1.6 on 2025-05-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('team1_score', models.IntegerField(blank=True, null=True)),
                ('team2_score', models.IntegerField(blank=True, null=True)),
                ('team1_result', models.CharField(max_length=100)),
                ('team2_result', models.CharField(max_length=100)),
                ('stadium', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
