# Generated by Django 5.2.3 on 2025-11-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        # DB에는 이미 game_id 컬럼이 PK로 존재하므로, 스키마 변경 없이
        # Django 상태만 맞춰준다.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='game',
                    name='id',
                    field=models.IntegerField(db_column='game_id', primary_key=True, serialize=False),
                ),
            ],
            database_operations=[],
        ),
    ]
