# Generated by Django 5.1.6 on 2025-06-16 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hitter',
            old_name='_2B',
            new_name='H_2B',
        ),
        migrations.RenameField(
            model_name='hitter',
            old_name='_3B',
            new_name='H_3B',
        ),
        migrations.RenameField(
            model_name='pitcher',
            old_name='_2B',
            new_name='H_2B',
        ),
        migrations.RenameField(
            model_name='pitcher',
            old_name='_3B',
            new_name='H_3B',
        ),
    ]
