# Generated by Django 5.1.6 on 2025-06-04 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hitter_Daily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=100)),
                ('player_id', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=50)),
                ('AB', models.PositiveIntegerField()),
                ('R', models.PositiveIntegerField()),
                ('H', models.PositiveIntegerField()),
                ('RBI', models.PositiveIntegerField()),
                ('HR', models.PositiveIntegerField()),
                ('SO', models.PositiveIntegerField()),
                ('SB', models.PositiveIntegerField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.game')),
            ],
        ),
        migrations.CreateModel(
            name='Pitcher_Daily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=100)),
                ('player_id', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=50)),
                ('IP', models.PositiveIntegerField()),
                ('H', models.PositiveIntegerField()),
                ('R', models.PositiveIntegerField()),
                ('ER', models.PositiveIntegerField()),
                ('BB', models.PositiveIntegerField()),
                ('SO', models.PositiveIntegerField()),
                ('HR', models.PositiveIntegerField()),
                ('BF', models.PositiveIntegerField()),
                ('AB', models.PositiveIntegerField()),
                ('NP', models.PositiveIntegerField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.game')),
            ],
        ),
        migrations.DeleteModel(
            name='Daily',
        ),
    ]
