# Generated by Django 5.2.4 on 2025-08-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitcher',
            name='stamina',
            field=models.FloatField(default=0),
        ),
    ]
