# Generated by Django 5.1.6 on 2025-06-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='player_id',
            field=models.CharField(max_length=100),
        ),
    ]
