# Generated by Django 5.2.1 on 2025-06-12 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitter_daily',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.hitter'),
        ),
        migrations.AlterField(
            model_name='pitcher_daily',
            name='player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cal.pitcher'),
        ),
    ]
