# Generated by Django 5.1.6 on 2025-06-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_hitter_daily_pitcher_daily_delete_daily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitcher_daily',
            name='IP',
            field=models.FloatField(),
        ),
    ]
