# Generated by hand to align address columns with existing DB schema (adress)
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_alter_game_id'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='parking',
                    name='address',
                    field=models.CharField(max_length=100, db_column='adress'),
                ),
                migrations.AlterField(
                    model_name='restaurant',
                    name='address',
                    field=models.CharField(max_length=100, db_column='adress'),
                ),
            ],
            database_operations=[],
        ),
    ]
