# Generated by Codex to align Game.id with existing DB column
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_add_missing_pitchers'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='game',
                    name='id',
                    field=models.IntegerField(primary_key=True, serialize=False),
                ),
            ],
            database_operations=[],
        ),
    ]
