# tothe_ballpark/.config/uwsgi/baseball.ini

[uwsgi]
chdir = /home/ubuntu/tothe_ballpark
module = baseball.wsgi:application
home = /home/ubuntu/tothe_ballpark/venv

uid = ubuntu
gid = ubuntu

socket = /home/ubuntu/tothe_ballpark/tmp/baseball.sock
chmod-socket = 666
chown-socket = ubuntu:ubuntu

enable-threads = true
master = true
vacuum = true
pidfile = /home/ubuntu/tothe_ballpark/tmp/baseball.pid
logto = /home/ubuntu/tothe_ballpark/log/uwsgi/@(exec://date +%Y-%m-%d).log
log-reopen = true
